### ISSUE TITLE
Crash on client when try to load connected glasses with OptiFabric and Optifine enabled

### ISSUE THREAD

**Issue by Neubulae** [grondag/exotic-blocks#3]
https://pastebin.com/ihrgyZve
Crash log.

**Comment by grondag** [comment]
Thank you for the issue report.

Sadly, I am not able to support Optifine.  It is a closed-source mod and make many big changes/assumptions about models and rendering, and offers no public API.

I might be able prevent this crash with some extra work, but it would likely crash at some different point because OF assumes vanilla JSON models.  So its not something I'm willing to invest time in.
